name: trustlaundry
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.4+4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  google_fonts: ^6.2.1
  encrypt: ^5.0.3
  mailer: ^6.3.0
  flutter_svg: ^2.0.10+1
  firebase_messaging: ^15.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.2
  widget_and_text_animator: ^1.1.5
  pin_code_fields: ^8.0.1
  flutter_launcher_icons: ^0.13.1
  ionicons: ^0.2.2
  firebase_auth: ^5.1.4
  location: ^6.0.2
  pdf: ^3.11.1
  share_plus: ^10.1.2
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  confirm_dialog: ^1.0.3
  firebase_storage: ^12.2.0
  cloud_firestore: ^5.2.1
  url_launcher: ^6.3.0
  carousel_slider_plus: ^7.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0
  skeletonizer: ^1.4.2
  flutter_tap_payment: ^0.2.1
  easy_stepper: ^0.8.5+1
  animated_digit: ^3.2.3
  lottie: ^3.1.2
  loading_animation_widget: ^1.2.1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  flutter_staggered_animations: ^1.1.1
  add_to_cart_animation: ^2.0.4
  flutter_bloc: ^8.1.6
  banner_carousel: ^1.2.1
  firebase_core: ^3.1.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/animations/

flutter_intl:
  enabled: true
